spring.application.name=Bus-Ticket-Booking
server.port=8085
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/busticketbooking
spring.datasource.username=root
spring.datasource.password=Ayush@2003



#spring.datasource.url=jdbc:mysql://10.10.167.197:3306/busticketbooking
#spring.datasource.username= capg
#spring.datasource.password=capg

spring.jpa.hibernate.ddl-auto=validate

#For local host connection
#spring.datasource.url=jdbc:mysql://localhost:3306/busticketbooking
#spring.datasource.username=root
#spring.datasource.password=Ayush@2003

spring.jpa.hibernate.ddl-auto=update
>>>>>>> feature/Ayush
spring.jpa.show-sql=true

jwt.secret=BusTicketBookingSecretKeyForJWTAuthenticationAndAuthorizationPurpose123
jwt.expiration=3600000

